version: "3"
services:
    discordbot:
        build: .
        restart: always
        expose:
            - "80"
        volumes:
            - ./data/discordbot:/data/discordbot
            - ./logs/discordbot:/logs/discordbot
            - ./discordbot:/opt/discordbot
        environment:
            DEPLOY: /data/discordbot
            DISCORD_TOKEN: ${DISCORD_TOKEN}
            DISCORD_CHANNEL_NAME: ${DISCORD_CHANNEL_NAME}
