version: "3"
services:
    notifyd:
        build: .
        restart: always
        network_mode: "host"
        ports:
            - "5050:5050"
        volumes:
            - ./data/notifyd:/data/notifyd
            - ./logs/notifyd:/logs/notifyd
        environment:
            DEPLOY: /data/notifyd
            DISCORD_TOKEN: ${DISCORD_TOKEN}
            NOTIFYD_TOKEN: "abc"
            DISCORD_CHANNEL_NAME: tv
            RECEIVE: "http://localhost:1234/receive-endpoint"
            PORT: 5050
            DEBUG: ${DEBUG}
